name: opendap-viewer
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - pip
  - nodejs=11.14.0
  - numpy
  - itk
  - ipywidgets=7.4.2
  - widgetsnbextension
  - pip:
      - bqplot
      - dask
      - distributed
      - ipywebrtc
      - itkwidgets
      - itk-io
      - matplotlib
      - netCDF4
      - numpy
      - plotly>=3.3.0
      - toolz
      - scikit-image
      - six
      - xarray
      - zstandard
