name: opendap-viewer
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - pip
  - nodejs=11.14.0
  - numpy
  - itk
  - ipywidgets=7.4.2
  - widgetsnbextension
  - pip:
      # - widgetsnbextension
      #- ipywidgets>=7.1.2
      - numpy
      - six
      - zstandard
      - ipywebrtc
      - bqplot
      - plotly>=3.3.0
